### ISSUE TITLE
Track your packet here dagi input

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/Package-Delivery-Website#1]
maketda inputning borderi yoq
![image](https://user-images.githubusercontent.com/79502241/114540065-8b293000-9c6e-11eb-8e50-763abbd378bf.png)
borderni olib tashlash kerak
![image](https://user-images.githubusercontent.com/79502241/114540129-9d0ad300-9c6e-11eb-891e-014c249ee4c1.png)

**Comment by ShokhrukhTurgunov** [comment]
boldi rahmat. Olib tashladim
